name: Notify Root Repository

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  notify-root-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Send Webhook to Root Repository
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.ROOT_REPO_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/ontargetcomputing/terraform-root/actions/workflows/lint.yml/dispatches \
          -d '{
            "ref": "main",
            "inputs": {
              "account": "terraform-submodule",
              "initiator": "${{ github.actor }}"
            }
          }'